/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




/* ====================== Includes =========================== */
#include "STM32_F103C6_GPIO_Driver.h"
#include "lcd.h"
#include "keypad.h"
#include "S7_segment.h"

/* ========== Prototypes ========= */
void clock_init();
extern void delay_ms(uint32_t delay);

/* =========== Main Program ========== */
int main(void)
{
	// Initializing the clock
	clock_init();

	// Initializing the LCD
	LCD_init();

	// Initializing the 7-segment
	Init_7_segment();

	LCD_write_string("HEY THERE !");
	delay_ms(500);
	LCD_clear_screen();

	// Variable to check pressed key of Keypad
	unsigned char key_pressed;

	// Array to store of 7 segments shapes
	unsigned char seg_Numbers[] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};

	// Array to store Numbers from 1 >>> 9 to be displayed on LCD
	unsigned char LCD_Numbers[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};

	// Loop to display the same number to LCD and 7-SEGMENT
	for (unsigned int i = 0; i < 11; i++)
	{
		// Display current number on the 7 segment
		MCAL_GPIO_WritePort(GPIO_PORTB, seg_Numbers[i] << 9);
		// We shifted by 9 as we used the First 9 Ports for Keypad and started connecting 7 segment from PB10

		// Display current number on the LCD
		LCD_write_char(LCD_Numbers[i]);
		// Delay to be able to see the change in numbers
		delay_ms(1000);  // 1 second delay
	}

	// Clear screen after displaying Numbers
	LCD_clear_screen();

	// Initializing the Keypad
	Keypad_init();

	LCD_write_string("Keypad is ready !");
	delay_ms(500);
	LCD_clear_screen();

	while(1)
	{
		key_pressed = Keypad_getkey();

		switch(key_pressed){
		case 'A':
			break;
		case '?':
			LCD_clear_screen();
			break;
		default:
			LCD_write_char(key_pressed);
			break;
		}
	}
}

/* ======== clock init definition ======= */
void clock_init()
{
	// Enable clock of Port A
	RCC_GPIO_PORTA_CLK_EN();

	// Enable clock of Port B
	RCC_GPIO_PORTB_CLK_EN();
}
